### PR TITLE
fix build failure

### PR DESCRIPTION
**Pull request by melezhik**
@ispyhumanfly I believe this should fix the build failure

### CODE REVIEW

**Comment by melezhik** [comment]
https://ci.sparrowhub.io/report/2726

**Comment by melezhik** [comment]
Hi @ispyhumanfly  , just a gentle reminder - please let me know if you are still interested in the fix? Thanks )))

**Comment by ispyhumanfly** [comment]
Hey @melezhik thank you for this fix!!! I got super busy with some other work stuff and didn't see this. Thank you!

**Comment by melezhik** [comment]
Sure. Welcome

**Pull request merged**
